"""
Django settings for bookapp project.

Generated by '02.django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '02.django-insecure-agpgvb##fcw(t4v7#l-mxxpk+fujzs0_ey2b5$ooehb2iwx!l_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    '02.django.contrib.admin',
    '02.django.contrib.auth',
    '02.django.contrib.contenttypes',
    '02.django.contrib.sessions',
    '02.django.contrib.messages',
    '02.django.contrib.staticfiles',
    'bookapp',
]

MIDDLEWARE = [
    '02.django.middleware.security.SecurityMiddleware',
    '02.django.contrib.sessions.middleware.SessionMiddleware',
    '02.django.middleware.common.CommonMiddleware',
    '02.django.middleware.csrf.CsrfViewMiddleware',
    '02.django.contrib.auth.middleware.AuthenticationMiddleware',
    '02.django.contrib.messages.middleware.MessageMiddleware',
    '02.django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bookapp.urls'

TEMPLATES = [
    {
        'BACKEND': '02.django.template.backends.02.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                '02.django.template.context_processors.debug',
                '02.django.template.context_processors.request',
                '02.django.contrib.auth.context_processors.auth',
                '02.django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': '02.django.db.backends.mysql',
        'NAME': 'django_db',
        'HOST': '1.13.248.209',
        'PORT': 3306,
        'USER': 'admin',
        'PASSWORD': 'Cyd@2022'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': '02.django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': '02.django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': '02.django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': '02.django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = '02.django.db.models.BigAutoField'
